version: "3"
services:
  haproxy:
    container_name: minemeld
    image: paloaltonetworks/minemeld:${MINEMELD_VERSION}
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    tmpfs:
      - /run
    volumes:
      - ${MINEMELD_LOCAL}:/opt/minemeld/local
      - ${MINEMELD_LOGS}:/opt/minemeld/log


      